from typing import Protocol


class Cache(Protocol):
    async def get(self, key: str) -> str | None: ...
    async def set(self, key: str, value: str, ttl_s: int | None = None) -> None: ...
    async def set_if_absent(self, key: str, value: str, ttl_s: int) -> bool: ...
    async def health(self) -> bool: ...
